use clinica2;

create view MEDICOS_ESPECIALIDADES_CARDIOLOGIA (NOMEMED,NUMEROCRM,ESTADOCRM)
AS SELECT M.NOMEMED,M.NUMEROCRM,M.ESTADOCRM FROM MEDICO M, POSSUEESPECIALIDADE PE
WHERE M.NUMEROCRM = PE.NUMEROCRM AND PE.IDESPECIALIDADE = 1;


select * from paciente where NOMEPACIENTE like '%joao%';